### ISSUE TITLE
Galaxy Tab S and Android 6

### ISSUE THREAD

**Issue by shinyford** [Chagall/notification-listener-service-example#10]
Hi!

I'm trying to use this (or at least, an app that uses its principles) on a Galaxy Tab S running Android 6.

I see that you've used it on a Lollipop, Android 5, phone, so I assume it can work: however, while it runs perfectly, there seems to be no way on that device for the user to navigate to the correct app permissions page to turn the BIND_NOTIFICATION_LISTENER_SERVICE permission on.

Just wondered if you'd hit that problem before, and if there were a solution?

Many thanks - great example of how to do this, BTW.

Cheers

Nic

**Comment by Chagall** [comment]
You can totally do that, here are the steps:

## Go to settings
![img](https://i.imgur.com/2qPkNnM.png)

## Select sound and notification
![img](https://i.imgur.com/UBCc1kK.png)

## Select notification access
![img](https://i.imgur.com/r4nLHsH.png)
