### ISSUE TITLE
How to actually build this?

### ISSUE THREAD

**Issue by luke-jr** [Chagall/notification-listener-service-example#11]
I installed Android Studio and loaded this, but I can't seem to find a way to actually get it to build...?

Or what is the recommended procedure to compile an apk from it?

**Comment by albertlieyingadrian** [comment]
Having the same problem here

**Comment by knight1O1** [comment]
> Having the same problem here

> I installed Android Studio and loaded this, but I can't seem to find a way to actually get it to build...?
> 
> Or what is the recommended procedure to compile an apk from it?

what kind of issue are u facing ? share screenshot or Error Message !

**Comment by Chagall** [comment]
I made this project a long time ago, when android studio was on version 2.3 or something. Since then a lot has changed on the android ecosystem, so I'm not even sure if this feature is still a thing. Tomorrow I'll try to compile this and see if I have any problems. @luke-jr @LieAlbertTriAdrian which operating system were you using.

**Comment by luke-jr** [comment]
Lubuntu

**Comment by abdul99ahad** [comment]
I'm trying to get it build. Things I had to set was just gradle and sdk version by going into the Project Structure. 
But now I'm getting `Gradle sync failed: Unsupported method: SyncIssue.getMultiLineMessage(). `

Any solution?

**Comment by abdul99ahad** [comment]
> I'm trying to get it build. Things I had to set was just gradle and sdk version by going into the Project Structure.
> But now I'm getting `Gradle sync failed: Unsupported method: SyncIssue.getMultiLineMessage(). `
> 
> Any solution?

Turns out my gradle version wasn't set to current one. Followed this link and it works. 
https://stackoverflow.com/questions/64409047/gradle-sync-failed-unsupported-method-syncissue-getmultilinemessage-androi

**Comment by Chagall** [comment]
Working on this right now, will update you guys in next few hours.

**Comment by Chagall** [comment]
**Ok folks here is the deal:** A lot of configuration files were using the standards of 5 years ago and that was causing a lot of problems,  some libraries were even deprecated and all of that stuff. So I updated all that I could to the newest or close to newest version: the android api is now targeting android 10, and gradle plugin and gradle wrapper are both updated to the latest version.

I advise you to pull from the master, or clone the repository again and try to compile it with these changes. Let me know if this worked for you guys. 

Additionaly I tested the app on my Samsung Galaxy S7 Android 8.0.0 and the app successfully intercepted a whatsapp notification, so it is still working properly even after all these years:

![img](https://i.imgur.com/RJKolrB.jpg)

**Comment by abdul99ahad** [comment]
Thanks Chagall. I don't know if this is the right place to ask you this but is there any way to get content of notifications as well? For example, if a person sends you a message so the app gets the name of that person and the message. Can you guide me a little about this?

**Comment by Chagall** [comment]
To be honest I don't remember anymore. The only thing I'm sure is that the place to get it is `onNotificationPosted.` 
Looking at the documentation I think the notification information is in the extras bundle. Something like this:

```
    @Override
    public void onNotificationPosted(StatusBarNotification sbn){
        Notification n = sbn.getNotification();
        Bundle b = n.extras;
        System.out.println(b.toString()); // I think this won't work, you will have to use the bundle to get key value pairs
    }

```
This documentation should help you:
https://developer.android.com/reference/android/service/notification/StatusBarNotification
https://developer.android.com/reference/android/app/Notification

Later today I will try to see if I can get some info from a  whatsapp notification, I'll let you know if I get it right.

**Comment by abdul99ahad** [comment]
Thanks, Chagall for your help. I've some questions regarding this is it okay if I email you or something? If that's okay, please share your email so I can clarify my concepts.

**Comment by Chagall** [comment]
Sure, it's: famp@operamail.com
Once you get it let me know and the I will close this issue, since the app is proven to be building correctly.

**Comment by abdul99ahad** [comment]
Thanks, I got it.
