### ISSUE TITLE
App not working in Huawei P10 lite

### ISSUE THREAD

**Issue by Lir10** [Chagall/notification-listener-service-example#12]
Hi, I've tested the app on my Huawei P10 lite Android 8. and it doesn't work - not getting any notifications even though I've enabled the notification permission from the android settings ... any idea ?

**Comment by Chagall** [comment]
Hmm which app were you testing? Whastapp, face or insta?

**Comment by Lir10** [comment]
WhatsApp

**Comment by Chagall** [comment]
Ok. Thanks for reporting, I'll try to look what could be wrong.

**Comment by Lir10** [comment]
It works now ... whitelisting the app from battery optimization worked

**Comment by Chagall** [comment]
Great! I'll mark this issue as closed then. have fun tinkering with the app :^)
