### ISSUE TITLE
in Background not working.Help

### ISSUE THREAD

**Issue by rajumark** [Chagall/notification-listener-service-example#6]
when app is open it is working fine but when i clear it from recent apps its not working 
-> tip: i think background services are not working (xiaomi red mi note 4 is my device )
-> please help me to fix it

**Comment by Chagall** [comment]
- When you clear the app from recent apps Android is calling the **onDestroy** method in the **Main.java** file

- When **onDestroy** is called, it unregisters the **ImageChangeBroadcastReceiver** (which was listening to the broadcasts send by the **NotificationListenerService** and changing the images).

- **NotificationListenerService** is still running in the background, but it is sending a broadcast that nobody is listening to. So if you want it to work with something else, you must implement a broadcast receiver that works in the background aswell

**Comment by rajumark** [comment]
Okay totally ...got it
Thanks for reply
You can remove library issue. #6
😊
