### ISSUE TITLE
Anadroid GO -  Oreo 8.1

### ISSUE THREAD

**Issue by lakesidepark** [Chagall/notification-listener-service-example#8]
Hello exists any way to implement this kind of listener into Android Oreo (https://developer.android.com/about/versions/oreo/android-8.0). Oreo /Android GO dont have the notification layer.

**Comment by Chagall** [comment]
I just tested this today on my Samsung Galaxy S7 Android Oreo 8.0.0 and it worked just fine: 

![img](https://i.imgur.com/RJKolrB.jpg)
